/*

Locator - Identifies the element on the page

DOM - Document Object Model
DOM is generated by the browser when the page is loaded
DOM represents the page structure in a tree format
DOM is API to interact with the page structure
Locators use DOM to identify the elements on the page


page.getByRole() to locate by explicit and implicit accessibility attributes.
page.getByText() to locate by text content.
page.getByLabel() to locate a form control by associated label's text.
page.getByPlaceholder() to locate an input by placeholder.
page.getByAltText() to locate an element, usually image, by its text alternative.
page.getByTitle() to locate an element by its title attribute.
page.getByTestId() to locate an element based on its data-testid attribute (other attributes can be configured

*/



import {test, expect, Locator} from "@playwright/test";

test("verify playwright locators", async({page})=>{

    await page.goto("https://demo.nopcommerce.com/");

// 1) page.getByAltText() to locate an element, usually image, by its text alternative.
// identifies images and similar elements based on alt attribute
    const logo:Locator = page.getByAltText("nopCommerce demo store");
    await expect(logo).toBeVisible();



// 2) page.getByText() - Find an element by the text it contains. You can match a substring, exact string, or a regular expression
// Locate by visible text
// Use this locator to find non interactive elements like div, span, p, h1-h6 etc
// For interactive elements like button, a, input etc use getByRole() instead


    // const text:Locator = page.getByText("Welcome to our store");
    // await expect(text).toBeVisible();
    await expect(page.getByText("Welcome to our store")).toBeVisible(); 
    await expect(page.getByText("Welcome to")).toBeVisible(); //susbtring match
    await expect(page.getByText(/Welcome\s+To\s+Our\s+Store/i)).toBeVisible(); //regex match
// i is case insensitive flag in regex


// 3) page.getByRole() to locate by explicit and implicit accessibility attributes.
// Use this locator to find interactive elements like button, a, input etc
/* Role locators include buttons, checkboxex, links, lists, tables,
    and many more and follow W3C specifications for ARIA role.

    role is not an attribute in the DOM, its an accessibility property derived from multiple attributes in the DOM
    Examples of attributes that contribute to role are: 
    <button> element has an implicit role of button
    <a> element with href attribute has an implicit role of link
    An element with attribute role="button" has an explicit role of button

    implicit - tag name defines the role
    explicit - role attribute defines the role

 */
    await page.getByRole('link', {name: 'Register'}).click();
    await expect(page.getByRole('heading', {name : 'Register'})).toBeVisible();
    // You can also use getByText to verify the heading
    // await expect(page.getByText('Register')).toBeVisible();


/*
4) page.getByLabel() - Locate form (signUp for, Login form) control
    by associated label's text.
    Labels are associated with form controls using <label> tag
    or aria-label/aria-labelledby attributes
    Ideeal for form fields with visible labels
*/
    await page.getByLabel('First name:').fill('Karthik');
    await page.getByLabel('Last name:').fill('Valiveti');
    await page.getByLabel('Email:').fill('saikarthikk06@gmail.com');


/*
5) page.getByPlaceholder() to locate a placeholder
Most of the times input box, serach box will have placeholder attribute
FIND THE ELEMENT USING PLACEHOLDER ATTRIBUTE
Best for input boxes without a label but having a placeholder
*/
    await page.getByPlaceholder('Search store').fill('Apple macbook pro');

/*
6) page.getByTitle() to locate an element by its title attribute.
Title attribute usually provides additional information about the element
Best for elements with title attribute
*/

await page.goto('http://127.0.0.1:5500/tests/app.html');

await expect(page.getByTitle('Home page link')).toHaveText('Home');
await expect(page.getByTitle('HyperText Markup Language')).toHaveText('HTML');

/*
7) page.getByTestId() to locate an element based on its data-testid attribute (other attributes can be configured)
When to use : When text or role based locators are unstable or not suitable

*/
    await expect(page.getByTestId('profile-email')).toHaveText('john.doe@example.com');
    await expect(page.getByTestId('profile-name')).toHaveText('John Doe');
    // Suppose if the attribute is data-qa-id instead of data-testid
    // then we need to configure testIdAttribute in playwright.config.ts
    // go to the file and add below line in "use" block
    // testIdAttribute: 'data-qa-id'
// so, you don't need to change the method here or even the attribute

})